<div class="block">
    <div class="block-header">
        <div class="block-title">Administration</div>
    </div>
    <div class="block-content">
        <div class="admin-icons">
            <a href="<?= $this->myBaseUrl("admin/rooms/") ?>"><img src="<?= $this->myBaseUrl('images/layout/admin_room.png') ?>" alt="" />Manage rooms</a>
            <a href="<?= $this->myBaseUrl("admin/booking/") ?>"><img src="<?= $this->myBaseUrl('images/layout/admin_booking.png') ?>" alt="" />Manage booking</a>
        </div>
    </div>
</div>